In [1]:
from transformers import AutoTokenizer, LlamaForCausalLM

llama_tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-3.2-1B", use_fast=True)
llama_model = LlamaForCausalLM.from_pretrained("meta-llama/Llama-3.2-1B")

/Users/alibayram/.pyenv/versions/3.13.3/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
from llama3_2.model import Llama3Model, LLAMA32_CONFIG_1B

llama_fs_model = Llama3Model(LLAMA32_CONFIG_1B)

In [3]:
import torch
import torch.nn as nn

fn = nn.SiLU()
fn2 = nn.functional.silu

In [4]:
example_input_fn = torch.randn(1, 4, 8)
example_output_fn = fn(example_input_fn)
print(example_output_fn)
example_output_fn = fn2(example_input_fn)
print(example_output_fn)

tensor([[[ 1.0134e+00,  1.5835e-01,  7.3086e-01,  4.8018e-01, -1.1894e-03,
          -1.6231e-01,  4.2688e-01,  2.5437e-01],
         [ 1.4345e-01,  7.7666e-01, -1.7897e-01, -2.5091e-01,  1.1267e+00,
          -2.7279e-01,  1.6801e+00,  9.1529e-01],
         [ 1.0538e-01,  1.6798e-02, -1.5177e-01,  5.7822e-01, -2.7722e-01,
           4.2604e-01, -1.0185e-02,  7.2041e-01],
         [ 2.8271e-02, -2.7567e-01, -2.3676e-01,  2.9576e-01,  7.1711e-02,
           6.1162e-02,  5.4641e-01,  2.4618e-02]]])
tensor([[[ 1.0134e+00,  1.5835e-01,  7.3086e-01,  4.8018e-01, -1.1894e-03,
          -1.6231e-01,  4.2688e-01,  2.5437e-01],
         [ 1.4345e-01,  7.7666e-01, -1.7897e-01, -2.5091e-01,  1.1267e+00,
          -2.7279e-01,  1.6801e+00,  9.1529e-01],
         [ 1.0538e-01,  1.6798e-02, -1.5177e-01,  5.7822e-01, -2.7722e-01,
           4.2604e-01, -1.0185e-02,  7.2041e-01],
         [ 2.8271e-02, -2.7567e-01, -2.3676e-01,  2.9576e-01,  7.1711e-02,
           6.1162e-02,  5.4641e-01,  2.4618e-02]

In [11]:
token = llama_tokenizer.encode("Hello")
token

[128000, 9906]

In [16]:
embedding = llama_model.model.embed_tokens(torch.tensor([[9906]]))
embedding.shape

torch.Size([1, 1, 2048])

In [18]:
model_output = llama_model.model(torch.tensor([[9906]]))
model_output

BaseModelOutputWithPast(last_hidden_state=tensor([[[-0.0714, -0.0281,  1.7906,  ...,  0.5309, -0.6187,  0.3760]]],
       grad_fn=<MulBackward0>), past_key_values=<transformers.cache_utils.DynamicCache object at 0x14d295bd0>, hidden_states=None, attentions=None)

In [21]:
model_output.last_hidden_state

tensor([[[-0.0714, -0.0281,  1.7906,  ...,  0.5309, -0.6187,  0.3760]]],
       grad_fn=<MulBackward0>)

In [5]:
llama_model

LlamaForCausalLM(
  (model): LlamaModel(
    (embed_tokens): Embedding(128256, 2048)
    (layers): ModuleList(
      (0-15): 16 x LlamaDecoderLayer(
        (self_attn): LlamaAttention(
          (q_proj): Linear(in_features=2048, out_features=2048, bias=False)
          (k_proj): Linear(in_features=2048, out_features=512, bias=False)
          (v_proj): Linear(in_features=2048, out_features=512, bias=False)
          (o_proj): Linear(in_features=2048, out_features=2048, bias=False)
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear(in_features=2048, out_features=8192, bias=False)
          (up_proj): Linear(in_features=2048, out_features=8192, bias=False)
          (down_proj): Linear(in_features=8192, out_features=2048, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm((2048,), eps=1e-05)
        (post_attention_layernorm): LlamaRMSNorm((2048,), eps=1e-05)
      )
    )
    (norm): LlamaRMSNorm((2048,), eps=1e-05)
    (rotary_emb):

In [6]:
from llama3_2.config import LlamaConfig
config = LlamaConfig()


In [7]:
from llama3_2.model_trfmrs import LlamaForCausalLM
llama_trfmrs_csl_model = LlamaForCausalLM(config)
llama_trfmrs_csl_model

LlamaForCausalLM(
  (model): LlamaModel(
    (embed_tokens): Embedding(128256, 2048)
    (layers): ModuleList(
      (0-15): 16 x LlamaDecoderLayer(
        (self_attn): LlamaAttention(
          (q_proj): Linear(in_features=2048, out_features=2048, bias=False)
          (k_proj): Linear(in_features=2048, out_features=512, bias=False)
          (v_proj): Linear(in_features=2048, out_features=512, bias=False)
          (o_proj): Linear(in_features=2048, out_features=2048, bias=False)
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear(in_features=2048, out_features=8192, bias=False)
          (up_proj): Linear(in_features=2048, out_features=8192, bias=False)
          (down_proj): Linear(in_features=8192, out_features=2048, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm()
        (post_attention_layernorm): LlamaRMSNorm()
      )
    )
    (norm): LlamaRMSNorm()
  )
  (lm_head): Linear(in_features=2048, out_features=128256, bias=Fal

In [8]:
from llama3_2.model_trfmrs import LlamaModel


llama_trfmrs_model = LlamaModel(config)
llama_trfmrs_model

LlamaModel(
  (embed_tokens): Embedding(128256, 2048)
  (layers): ModuleList(
    (0-15): 16 x LlamaDecoderLayer(
      (self_attn): LlamaAttention(
        (q_proj): Linear(in_features=2048, out_features=2048, bias=False)
        (k_proj): Linear(in_features=2048, out_features=512, bias=False)
        (v_proj): Linear(in_features=2048, out_features=512, bias=False)
        (o_proj): Linear(in_features=2048, out_features=2048, bias=False)
      )
      (mlp): LlamaMLP(
        (gate_proj): Linear(in_features=2048, out_features=8192, bias=False)
        (up_proj): Linear(in_features=2048, out_features=8192, bias=False)
        (down_proj): Linear(in_features=8192, out_features=2048, bias=False)
        (act_fn): SiLU()
      )
      (input_layernorm): LlamaRMSNorm()
      (post_attention_layernorm): LlamaRMSNorm()
    )
  )
  (norm): LlamaRMSNorm()
)

In [ ]:
# llama_model.model state_dict
llama_model.model.state_dict().keys()

In [22]:
llama_trfmrs_model.load_state_dict(llama_model.model.state_dict())

<All keys matched successfully>

In [23]:
llama_trfmrs_model_output = llama_trfmrs_model(torch.tensor([[9906]]))
llama_trfmrs_model_output.shape

RuntimeError: shape '[1, 1, 4, 64]' is invalid for input of size 512